import json
from pathlib import Path


class FrameSimulator:
    """
    Simulates video frames generated by a docked drone.
    """

    def __init__(self, data_path: str = "data/frames.json"):
        self.data_path = Path(data_path)
        self.frames = self._load_frames()

    def _load_frames(self):
        with open(self.data_path, "r", encoding="utf-8") as file:
            return json.load(file)

    def get_frames(self):
        """
        Return all simulated frames.
        """
        return self.frames

    def stream_frames(self):
        """
        Simulate a frame-by-frame video stream.
        """
        for frame in self.frames:
            yield frame