import json
from pathlib import Path


class TelemetrySimulator:
    """
    Simulates telemetry generated by a docked drone.
    """

    def __init__(self, data_path: str = "data/telemetry.json"):
        self.data_path = Path(data_path)
        self.telemetry = self._load_telemetry()

    def _load_telemetry(self):
        with open(self.data_path, "r", encoding="utf-8") as file:
            return json.load(file)

    def get_telemetry(self):

        return [
            {
                "timestamp": "00:00",
                "location": "main_gate",
                "latitude": 18.5204,
                "longitude": 73.8567,
                "altitude": 25.0
            },
            {
                "timestamp": "00:01",
                "location": "main_gate",
                "latitude": 18.5204,
                "longitude": 73.8567,
                "altitude": 25.0
            },
            {
                "timestamp": "00:03",
                "location": "main_gate",
                "latitude": 18.5204,
                "longitude": 73.8567,
                "altitude": 25.0
            },
            {
                "timestamp": "00:06",
                "location": "main_gate",
                "latitude": 18.5204,
                "longitude": 73.8567,
                "altitude": 25.0
            },
            {
                "timestamp": "00:08",
                "location": "main_gate",
                "latitude": 18.5204,
                "longitude": 73.8567,
                "altitude": 25.0
            },
            {
                "timestamp": "00:09",
                "location": "main_gate",
                "latitude": 18.5204,
                "longitude": 73.8567,
                "altitude": 25.0
            },
            {
                "timestamp": "00:12",
                "location": "main_gate",
                "latitude": 18.5204,
                "longitude": 73.8567,
                "altitude": 25.0
            }
        ]

    def stream_telemetry(self):
        """
        Simulate a real-time telemetry stream.
        """
        for record in self.telemetry:
            yield record