import json
from pathlib import Path


class TelemetrySimulator:
    """
    Simulates telemetry generated by a docked drone.
    """

    def __init__(self, data_path: str = "data/telemetry.json"):
        self.data_path = Path(data_path)
        self.telemetry = self._load_telemetry()

    def _load_telemetry(self):
        with open(self.data_path, "r", encoding="utf-8") as file:
            return json.load(file)

    def get_telemetry(self):
        return self.telemetry

    def stream_telemetry(self):
        """
        Simulate a real-time telemetry stream.
        """
        for record in self.telemetry:
            yield record